---
- name: Update and reboot
  # note: your *hosts* section will likely be differnt as this is group I created for my REd Hat hosts in Ansible Tower itself.
  hosts: rhel_hosts
  gather_facts: no
  tasks:
    - name: Upgrade all packages
      yum:
      name: '*'
      state: latest
			
    - name: Reboot servers
      reboot: per_reboot_delay:90
	 msg: "!!!Attention, server will be rebooted in 90 seconds!!!"
